<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AreasTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('areas')->insert([

            // --------------------
            // OFICINAS
            // --------------------
            [
                'id' => 1,
                'name' => 'OFICINA GENERAL DE ATENCION AL CIUDADANO Y GESTION DOCUMENTAL',
                'code' => 'OGACGD',
                'description' => 'OFICINA GENERAL DE ATENCION AL CIUDADANO Y GESTION DOCUMENTAL',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'ATENCION AL CIUDADANO Y GESTION DOCUMENTAL',
            ],
            [
                'id' => 2,
                'name' => 'OFICINA GENERAL DE ADMINISTRACION',
                'code' => 'OGA',
                'description' => 'OFICINA GENERAL DE ADMINISTRACION',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'ADMINISTRACION',
            ],
            [
                'id' => 3,
                'name' => 'OFICINA DE ADMINISTRACION FINANCIERA',
                'code' => 'OAF',
                'description' => 'OFICINA DE ADMINISTRACION FINANCIERA',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'ADMINISTRACION FINANCIERA',
            ],
            [
                'id' => 4,
                'name' => 'OFICINA DE ABASTECIMIENTO',
                'code' => 'OAB',
                'description' => 'OFICINA DE ABASTECIMIENTO',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'ABASTECIMIENTO',
            ],
            [
                'id' => 5,
                'name' => 'OFICINA DE GESTION DE RECURSOS HUMANOS',
                'code' => 'OGRH',
                'description' => 'OFICINA DE GESTION DE RECURSOS HUMANOS',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'GESTION DE RECURSOS HUMANOS',
            ],
            [
                'id' => 6,
                'name' => 'OFICINA DE TECNOLOGIAS DE LA INFORMACION',
                'code' => 'OTI',
                'description' => 'OFICINA DE TECNOLOGIAS DE LA INFORMACION',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'TECNOLOGIAS DE LA INFORMACION',
            ],
            [
                'id' => 7,
                'name' => 'OFICINA GENERAL DE ASESORIA JURIDICA',
                'code' => 'OGAJ',
                'description' => 'OFICINA GENERAL DE ASESORIA JURIDICA',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'ASESORIA JURIDICA',
            ],
            [
                'id' => 8,
                'name' => 'OFICINA GENERAL DE PLANEAMIENTO Y PRESUPUESTO',
                'code' => 'OGPP',
                'description' => 'OFICINA GENERAL DE PLANEAMIENTO Y PRESUPUESTO',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'PLANEAMIENTO Y PRESUPUESTO',
            ],
            [
                'id' => 9,
                'name' => 'OFICINA DE PRESUPUESTO',
                'code' => 'OP',
                'description' => 'OFICINA DE PRESUPUESTO',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'PRESUPUESTO',
            ],
            [
                'id' => 10,
                'name' => 'OFICINA DE PLANEAMIENTO, MODERNIZACION E INVERSIONES',
                'code' => 'OPMI',
                'description' => 'OFICINA DE PLANEAMIENTO, MODERNIZACION E INVERSIONES',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'PLANEAMIENTO, MODERNIZACION E INVERSIONES',
            ],

            // --------------------
            // GERENCIAS
            // --------------------
            [
                'id' => 11,
                'name' => 'ALCALDIA',
                'code' => 'ALC',
                'description' => 'ALCALDIA',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'ALCALDIA',
            ],
            [
                'id' => 12,
                'name' => 'GERENCIA MUNICIPAL',
                'code' => 'GM',
                'description' => 'GERENCIA MUNICIPAL',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'MUNICIPAL',
            ],
            [
                'id' => 13,
                'name' => 'GERENCIA DE ADMINISTRACION TRIBUTARIA',
                'code' => 'GAT',
                'description' => 'GERENCIA DE ADMINISTRACION TRIBUTARIA',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'ADMINISTRACION TRIBUTARIA',
            ],

            // SUBGERENCIAS DE GAT
            [
                'id' => 14,
                'name' => 'SUB GERENCIA DE RENTAS',
                'code' => 'SGR',
                'description' => 'SUB GERENCIA DE RENTAS',
                'is_active' => true,
                'parent_id' => 13,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'RENTAS',
            ],
            [
                'id' => 15,
                'name' => 'SUB GERENCIA DE FISCALIZACION Y EJECUCION COACTIVA',
                'code' => 'SGFEC',
                'description' => 'SUB GERENCIA DE FISCALIZACION Y EJECUCION COACTIVA',
                'is_active' => true,
                'parent_id' => 13,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'FISCALIZACION Y EJECUCION COACTIVA',
            ],

            [
                'id' => 16,
                'name' => 'GERENCIA DE DESARROLLO ECONOMICO',
                'code' => 'GDE',
                'description' => 'GERENCIA DE DESARROLLO ECONOMICO',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'DESARROLLO ECONOMICO',
            ],

            // SUBGERENCIAS DE GDE
            [
                'id' => 17,
                'name' => 'SUB GERENCIA DE DESARROLLO ECONOMICO Y PRODUCTIVO',
                'code' => 'SGDEP',
                'description' => 'SUB GERENCIA DE DESARROLLO ECONOMICO Y PRODUCTIVO',
                'is_active' => true,
                'parent_id' => 16,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'DESARROLLO ECONOMICO Y PRODUCTIVO',
            ],
            [
                'id' => 18,
                'name' => 'SUB GERENCIA DE COMERCIO, LICENCIAS Y CONTROL SANITARIO',
                'code' => 'SGCLCS',
                'description' => 'SUB GERENCIA DE COMERCIO, LICENCIAS Y CONTROL SANITARIO',
                'is_active' => true,
                'parent_id' => 16,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'COMERCIO, LICENCIAS Y CONTROL SANITARIO',
            ],

            [
                'id' => 19,
                'name' => 'GERENCIA DE DESARROLLO TERRITORIAL E INFRAESTRUCTURA',
                'code' => 'GDTI',
                'description' => 'GERENCIA DE DESARROLLO TERRITORIAL E INFRAESTRUCTURA',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'DESARROLLO TERRITORIAL E INFRAESTRUCTURA',
            ],

            // SUBGERENCIAS DE GDTI
            [
                'id' => 20,
                'name' => 'SUB GERENCIA DE DESARROLLO TERRITORIAL',
                'code' => 'SGDT',
                'description' => 'SUB GERENCIA DE DESARROLLO TERRITORIAL',
                'is_active' => true,
                'parent_id' => 19,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'DESARROLLO TERRITORIAL',
            ],
            [
                'id' => 21,
                'name' => 'SUB GERENCIA DE INFRAESTRUCTURA',
                'code' => 'SGI',
                'description' => 'SUB GERENCIA DE INFRAESTRUCTURA',
                'is_active' => true,
                'parent_id' => 19,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'INFRAESTRUCTURA',
            ],

            [
                'id' => 22,
                'name' => 'GERENCIA DE SERVICIOS MUNICIPALES Y GESTION AMBIENTAL',
                'code' => 'GSMA',
                'description' => 'GERENCIA DE SERVICIOS MUNICIPALES Y GESTION AMBIENTAL',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'SERVICIOS MUNICIPALES Y GESTION AMBIENTAL',
            ],

            // SUBGERENCIAS DE GSMA
            [
                'id' => 23,
                'name' => 'SUB GERENCIA DE PARTICIPACION Y SEGURIDAD CIUDADANA',
                'code' => 'SGPSC',
                'description' => 'SUB GERENCIA DE PARTICIPACION Y SEGURIDAD CIUDADANA',
                'is_active' => true,
                'parent_id' => 22,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'PARTICIPACION Y SEGURIDAD CIUDADANA',
            ],
            [
                'id' => 24,
                'name' => 'SUB GERENCIA DE SERVICIOS MUNICIPALES',
                'code' => 'SGSM',
                'description' => 'SUB GERENCIA DE SERVICIOS MUNICIPALES',
                'is_active' => true,
                'parent_id' => 22,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'SERVICIOS MUNICIPALES',
            ],
            [
                'id' => 25,
                'name' => 'SUB GERENCIA AMBIENTAL',
                'code' => 'SGA',
                'description' => 'SUB GERENCIA AMBIENTAL',
                'is_active' => true,
                'parent_id' => 22,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'AMBIENTAL',
            ],

            [
                'id' => 26,
                'name' => 'GERENCIA DE DESARROLLO SOCIAL',
                'code' => 'GDS',
                'description' => 'GERENCIA DE DESARROLLO SOCIAL',
                'is_active' => true,
                'parent_id' => null,
                'type_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'DESARROLLO SOCIAL',
            ],

            // SUBGERENCIAS DE GDS
            [
                'id' => 27,
                'name' => 'SUB GERENCIA DE SERVICIOS SOCIALES',
                'code' => 'SGSS',
                'description' => 'SUB GERENCIA DE SERVICIOS SOCIALES',
                'is_active' => true,
                'parent_id' => 26,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'SERVICIOS SOCIALES',
            ],
            [
                'id' => 28,
                'name' => 'SUB GERENCIA DE PROGRAMAS SOCIALES',
                'code' => 'SGPS',
                'description' => 'SUB GERENCIA DE PROGRAMAS SOCIALES',
                'is_active' => true,
                'parent_id' => 26,
                'type_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'short_name' => 'PROGRAMAS SOCIALES',
            ],
        ]);
    }
}
